version: "3.7"
services:
  app:
    container_name: prueba_app
    ports:
      - 3000:3000
    build:
      context: ./prueba-club
    depends_on:
      - db
      - rabbitmq
    restart: always
    networks:
      - mysql_network
  notifications:
    container_name: prueba_notifications
    build:
      context: ./prueba-notifications
    depends_on:
      - rabbitmq
    restart: always
    networks:
      - mysql_network
  db:
    container_name: prueba_mysql
    image: mysql:8.4
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    hostname: mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysqldb
      MYSQL_DATABASE: prueba_club
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./mysql/scripts:/docker-entrypoint-initdb.d:ro
    command: ["mysqld", "--mysql-native-password=ON"]
    ports:
      - 3307:3306
    
    networks:           
      - mysql_network
  rabbitmq:
    image: rabbitmq:3.11-management-alpine
    container_name: prueba_rabbitmq
    restart: always
    hostname: prueba_rabbitmq
    ports:
      - 5673:5672
      - 15673:15672
    volumes:
      - ~/.docker-conf/prueba_rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/prueba_rabbitmq/log/:/var/log/rabbitmq
    environment:
     - RABBITMQ_DEFAULT_PASS=passw123
     - RABBITMQ_DEFAULT_USER=admin
    networks:
      - mysql_network


networks:
  mysql_network:
    driver: bridge